# Generated by Django 2.2.2 on 2019-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0002_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='left_right',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
