# Generated by Django 2.2.2 on 2019-07-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0003_configuration_left_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('photo', models.URLField()),
            ],
        ),
    ]
